#!/usr/bin/env python3
"""Render the four built-in DIGITAL kick one-shots into a C header.

They are synthesised here, offline, rather than shipped as recordings, so the
module carries no third-party audio and needs no file I/O to make a sound.
Each is mono 44.1 kHz int16 with a 5 ms fade at the end, LOUDNESS-matched to
the analog kicks (first 150 ms RMS = 0.35, peak capped at 0.95) so the A/D MIX
knob blends like-for-like instead of doubling as a volume knob. The same rule
is applied to user WAVs at load time (dsp/hkh_samples.c). Users replace any of
them with their own WAV (README).

  1 PUNCH  modern techno sample kick: fast sweep, clicky transient, tight
  2 SUB    long deep sub kick for rumble techno
  3 CRUSH  a punchy kick through 11 kHz sample-and-hold and 6-bit words
  4 HARD   a hard-clipped distorted kick, lowpassed: the gnarly one
"""
import math
import pathlib
import sys

SR = 44100
NAMES = ["PUNCH", "SUB", "CRUSH", "HARD"]


class Noise:
    def __init__(self, seed):
        self.s = seed

    def __call__(self):
        self.s = (1103515245 * self.s + 12345) & 0x7FFFFFFF
        return self.s / 0x3FFFFFFF - 1.0


def sweep_kick(seconds, f_end, f_sweep, tau_sweep, f_slow, tau_slow, t60, attack=0.0003):
    out, ph = [], 0.0
    k = 6.9078 / t60
    for i in range(int(seconds * SR)):
        t = i / SR
        f = f_end + f_sweep * math.exp(-t / tau_sweep) + f_slow * math.exp(-t / tau_slow)
        ph += 2 * math.pi * f / SR
        env = math.exp(-k * t) * min(1.0, t / attack if attack > 0 else 1.0)
        out.append(math.sin(ph) * env)
    return out


def punch():
    n = Noise(1)
    body = sweep_kick(0.45, 52, 130, 0.012, 22, 0.06, 0.32)
    out, prev = [], 0.0
    for i, b in enumerate(body):
        t = i / SR
        x = n()
        click = (x - prev) * 0.55 * math.exp(-t / 0.0016)   # first difference = bright
        prev = x
        out.append(math.tanh(1.8 * (b + click)) / math.tanh(1.8))
    return out


def sub():
    n = Noise(2)
    body = sweep_kick(1.3, 42, 26, 0.045, 14, 0.12, 1.25, attack=0.001)
    out, lp = [], 0.0
    for i, b in enumerate(body):
        t = i / SR
        lp += 0.2 * (n() - lp)
        out.append(math.tanh(1.25 * b) / math.tanh(1.25) + lp * 0.25 * math.exp(-t / 0.002))
    return out


def crush():
    body = sweep_kick(0.4, 56, 160, 0.010, 30, 0.05, 0.26)
    out, held = [], 0.0
    for i, b in enumerate(body):
        if i % 4 == 0:                        # 11025 Hz sample-and-hold
            held = round(math.tanh(1.5 * b) / math.tanh(1.5) * 31) / 31   # 6-bit
        out.append(held)
    return out


def hard():
    body = sweep_kick(0.5, 55, 245, 0.025, 40, 0.08, 0.38)
    out, lp = [], 0.0
    a = 1 - math.exp(-2 * math.pi * 5000 / SR)
    for b in body:
        y = math.tanh(7.0 * b)
        lp += a * (y - lp)
        out.append(lp)
    return out


TARGET_RMS = 0.35     # first 150 ms, matches dsp/hkh_samples.c HKH_TARGET_RMS
PEAK_CAP = 0.95


def finish(x):
    fade = int(0.005 * SR)
    for i in range(fade):
        x[len(x) - fade + i] *= 1.0 - (i + 1) / fade
    head = x[:int(0.15 * SR)]
    rms = math.sqrt(sum(v * v for v in head) / len(head))
    peak = max(abs(v) for v in x)
    scale = min(TARGET_RMS / rms, PEAK_CAP / peak) * 32767
    return [max(-32767, min(32767, round(v * scale))) for v in x]


def main():
    kicks = [finish(f()) for f in (punch, sub, crush, hard)]
    lines = ["/* Generated by scripts/gen_digital_kicks.py. Do not edit. */",
             "#include <stdint.h>"]
    for i, k in enumerate(kicks):
        lines.append(f"static const int16_t hkh_dk{i}[{len(k)}] = {{")
        for j in range(0, len(k), 24):
            lines.append(",".join(str(v) for v in k[j:j + 24]) + ",")
        lines.append("};")
    lines.append("static const int16_t *const hkh_dk_data[4] = {hkh_dk0, hkh_dk1, hkh_dk2, hkh_dk3};")
    lines.append("static const int hkh_dk_len[4] = {" + ",".join(str(len(k)) for k in kicks) + "};")
    lines.append("static const char *const hkh_dk_name[4] = {" + ",".join(f'"{n}"' for n in NAMES) + "};")
    out = pathlib.Path(sys.argv[1])
    text = "\n".join(lines) + "\n"
    if not out.exists() or out.read_text() != text:   # keep make-style timestamps quiet
        out.write_text(text)


if __name__ == "__main__":
    main()
